version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: ns-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_pass
    networks:
      - backend_net
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"

  web:
    build: ./web
    container_name: ns-web
    depends_on:
      - db
    cap_add:
      - NET_ADMIN  # per poter modificare le rotte
    networks:
      dmz_net:
        ipv4_address: 10.20.0.10
      backend_net: {}
      admin_net: {}
    ports:  # (De-commentare solo se devi testare dal tuo browser host)
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_pass
      MYSQL_DB: webapp_db
    command: >
      sh -c "
      sleep 10;
      ip route add 10.10.0.0/24 via 10.20.0.254;
      apache2-foreground"
    volumes:
      - ./web:/var/www/html
      - /var/www/html/uploads

  handler:
    build: ./handler
    container_name: ns-handler
    networks:
      - admin_net
    # ports: #
    #   - "2222:22"
    restart: unless-stopped

  client:
    build: ./client
    container_name: ns-client
    cap_add:
      - NET_ADMIN
    networks:
      client_net:
        ipv4_address: 10.10.0.2
    command: >
      sh -c "
      ip route add 10.20.0.0/24 via 10.10.0.254;
      tail -f /dev/null
      "
    tty: true
    stdin_open: true

  attacker:
    build: ./attacker
    container_name: ns-attacker
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      client_net:
        ipv4_address: 10.10.0.3
    command: >
      sh -c "
      ip route add 10.20.0.0/24 via 10.10.0.254;
      tail -f /dev/null
      "
    tty: true
    stdin_open: true
    
  # Attacker's site for CSRF
  web_evil:
    build: ./web_evil
    container_name: ns-web_evil
    ports:
      - "8080:8080"
    volumes:
      - ./web_evil:/var/www/html
    networks:
      client_net:
        ipv4_address: 10.10.0.4
    command: >
      sh -c "ip route add 10.20.0.0/24 via 10.10.0.254;
      tail -f /dev/null;
      apache2-foreground"
    
  router:
    build: ./router
    container_name: ns-router
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      client_net:
        ipv4_address: 10.10.0.254
      dmz_net:
        ipv4_address: 10.20.0.254
    restart: unless-stopped

networks:
  client_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
  backend_net:
    driver: bridge
  admin_net:
    driver: bridge

volumes:
  db_data:
