version: '3.3'

services:
  db:
    image: mariadb:latest
    container_name: ns-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ns-network
    expose:
      - "3306"

  # Web Application
  web:
    build: ./web
    container_name: ns-web
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_pass
      MYSQL_DB: webapp_db
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - /var/www/html/uploads  # Exclude uploads from host mount
    networks:
      - ns-network
    command: sh -c "sleep 10 && apache2-foreground"

  # Attacker's site for CSRF
  web_evil:
    build: ./web_evil
    container_name: ns-web_evil
    ports:
      - "8080:8080"
    volumes:
      - ./web_evil:/var/www/html
    networks:
      - ns-network
    command: sh -c "apache2-foreground"

  ## Admin's PC
  handler:
    build: ./handler
    container_name: ns-handler
    ports:
      - "2222:22"
    networks:
      - ns-network

  ## Random User of the webapp
  client:
    build: ./client
    container_name: ns-client
    networks:
      - ns-network
    stdin_open: true
    tty: true

networks:
  ns-network:
    driver: bridge

volumes:
  db_data:
